name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Publish package to npm
    runs-on: ubuntu-latest

    permissions:
      contents: write # create tags and release notes
      issues: write
      pull-requests: write
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for semantic-release

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build types
        run: npm run build:types

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
